# Generated by Django 5.0.2 on 2024-03-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
    ]
