# Generated by Django 5.0.2 on 2024-03-04 19:09

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', editable=False, length=10, max_length=20, prefix='cat', unique=True),
        ),
    ]
